import os

BASE_URL_MS_WAREHOUSE = os.getenv("BASE_URL_MS_WAREHOUSE")
CONDUCTOR_BASE_URL = os.getenv("CONDUCTOR_BASE_URL")
CONDUCTOR_KEY_ID = os.getenv("CONDUCTOR_KEY_ID")
CONDUCTOR_KEY_SECRET = os.getenv("CONDUCTOR_KEY_SECRET")
